#define     IDD_SOURCEA         110
#define     IDD_SOURCEB         111
#define     IDD_MERGED          112
#define     IDD_X1              114
#define     IDD_Y1              115
#define     IDD_EXTX1           120  
#define     IDD_EXTY1           121  
#define     IDD_X2              116
#define     IDD_Y2              117
#define     IDD_EXTX2           122
#define     IDD_EXTY2           123
#define     IDD_X3              118
#define     IDD_Y3              119
#define     IDD_UNION           125
#define     IDD_INTERSECT       126
#define     IDD_SOURCEA_PATH    132
#define     IDD_SOURCEB_PATH    133
#define     IDD_MERGED_PATH     134
#define     IDD_VIEW_A          128
#define     IDD_VIEW_B          129
#define     IDD_DRAW_AREA       138
#define     IDD_MERGE_POINT     139
#define     IDD_X4              140
#define     IDD_Y4              141
#define     IDD_DIRLIST         142 
#define     IDD_RESET           144


