/****************************** SAVE DIALOG *********************************/

#define  ID_FEDIT                 401
#define  ID_DIRTXT                403
#define  ID_LSTBOX                404

#define  RGBBASE                  300

#define  CPI24                    301                        /* RGB FORMATS */
#define  TIF24                    302
#define  EPS24                    303
#define  TGA16                    304
#define  TGA24                    305
#define  TGA32                    306
#define  PMDIB24                  307                      /* new additions */
#define  WNDIB24                  308                      /* new additions */
#define  OIC24                    309

#define  CMFORMAT                 309
#define  CPI                      309                           /* COLORMAP */
#define  TIF                      310
#define  TGA                      311
#define  PCX                      312
#define  GIF                      313
#define  PMDIB                    314                      /* new additions */
#define  WNDIB                    315                      /* new additions */
#define  EPS                      316

#define  CLASSEDIT                500
