
#define   NO_ERROR                0
#define   LAST_USED               -137
#define   EC_ERROR                -99
#define   EC_SETHOT               -100
#define   EC_UFILETYPE            -101
#define   EC_OPENDLG              -102
#define   EC_SAVEDLG              -103
#define   EC_NOMEM                -104
#define   EC_RDHDR                -105
#define   EC_GSHADES              -106
#define   EC_RTGALS               -107
#define   EC_RTGAHDR              -108
#define   EC_RTIFLS               -109
#define   EC_RTIFHDR              -110
#define   EC_RTIFTAGS             -111
#define   EC_RPCXLS               -112
#define   EC_RPCXHDR              -113
#define   EC_UNGIF                -114
#define   EC_WRHDR                -115
#define   EC_UNTIFMON             -116
#define   EC_UNTIFCOMP            -117
#define   EC_SAMPIX               -118
#define   EC_BIGSTRIPS            -119

#define   EC_MEMORY1              -120
#define   EC_MEMORY2              -121
#define   EC_MEMORY3              -122
#define   EC_MEMORY4              -123
#define   EC_MEMORY5              -124
#define   EC_FILEREAD1            -125
#define   EC_FILEREAD2            -126
#define   EC_FILEWRITE1           -127
#define   EC_FILEWRITE2           -128
#define   EC_PALETTE              -129
#define   EC_INVALIDIMAGE         -130
#define   EC_NOFILENAME           -131
#define   EC_INVALID_FILENAME     -132
#define   EC_INVALID_PATH         -133
#define   EC_IMAGE_TOO_WIDE       -134
#define   EC_OIC_IMAGE_TOO_WIDE   -135
#define   EC_OIC_IMAGE_IS_LINES   -136
#define   EC_MERGE_TOO_WIDE       -137
#define   EC_NODISK               -138


/**************************** SCAN SPECIFIC ERRORS **************************/

#define   EC_PRESCAN             -160
#define   EC_SCAN                -161
#define   EC_NOSCANNER           -162
#define   EC_HARDWARE            -163
#define   EC_AOI                 -164



/* These are unknowns with duplicate numbers */
#define   EC_DLG                 -100  /* failed Create Dialog */
#define   EC_CREATEWND           -103  /* Failed to Create Window */
#define   EC_WINDOW              -107  /* invalid window, no window */
#define   EC_PAL                 -108  /* invalid palette handle */




// New for 3.1

#define   USER_ABANDON           -32768
