/*----------------------------- RESOURCES ----------------------------------*/

#define IMGPREP_ICON            30
#define IDC_CROSSHAIR           31
#define IDS_APPNAME             32
#define IMGPREP_MENU            33
#define MERGE_ICON              34
#define CLIP_ICON               35
#define COMBINE_ICON            36


#define RCFMT_NONE           0
#define RCFMT_CPI            1             
#define RCFMT_TIF            2
#define RCFMT_PS             3
#define RCFMT_TGA            4
#define RCFMT_PCX            5
#define RCFMT_GIF            6
#define RCFMT_PMDIB          7
#define RCFMT_WNDIB          8
#define RCFMT_WMF            9
#define RCFMT_DVA            10



#define   RC_STUB                           412

#define  RC_TYPE_BASE                       300
#define  RC_TYPE_CPI                        301 
#define  RC_TYPE_TIF                        302
#define  RC_TYPE_EPS                        303
#define  RC_TYPE_TGA                        304
#define  RC_TYPE_PCX                        305 
#define  RC_TYPE_GIF                        306
#define  RC_TYPE_PMDIB                      307
#define  RC_TYPE_WNDIB                      308
#define  RC_TYPE_WMF                        309
#define  RC_TYPE_DVA                        310

#define  RC_CLASS_BASE                      320
#define  RC_CLASS_RGB                       320
#define  RC_CLASS_CM                        321
#define  RC_CLASS_GRAY                      322
#define  RC_CLASS_BW                        323

#define  RC_CLASS_RGB16                     330
#define  RC_CLASS_CM16                      331
#define  RC_CLASS_GRAY16                    332

#define  RC_PAL_IMG                         340
#define  RC_PAL_DEF                         341
#define  RC_PAL_OPT                         342
#define  RC_PAL_GRAY                        343
#define  RC_PAL_BW                          344

#define  RC_PAL_IMG16                       350
#define  RC_PAL_DEF16                       351
#define  RC_PAL_OPT16                       352
#define  RC_PAL_GRAY16                      353

#define  RC_DITH_BASE                       360
#define  RC_DITH_NO                         360
#define  RC_DITH_BAY                        361
#define  RC_DITH_FS                         362
#define  RC_DITH_FS2                        363

#define  RC_BLANK                           370

#define   RCP_DP256                         380         
#define   RCP_DP8                           381         
#define   RCP_DP16                          382         
#define   RCP_OP256                         383         
#define   RCP_OP8                           384         
#define   RCP_OP16                          385         
#define   RCP_GP256                         386         
#define   RCP_GP64                          387         
#define   RCP_GP16                          388         
#define   RCP_GP8                           389         
#define   RCP_BP                            390      
#define   RCP_IP256                         391      

#define   RC_PRO_BASE                       400   
#define   RC_LIT                            400   
#define   RC_REDU                           401   
#define   RC_FS                             402   
#define   RC_BAY8                           403   
#define   RC_UQUA                           404   
#define   RC_UQUA8                          405   
#define   RC_GSUM                           406   
#define   RC_LEVL                           407   
#define   RC_DEIDX                          408   
#define   RC_G2BW                           409   
#define   RC_GBAY                           410
#define   RC_GFS                            411


/**************************** Set Hot Key Dialog ****************************/

#define     ID_BOGUS            373
#define     ID_HOTKEY           140


/*  Save report dialog  */

#define   SR_FILENAME      200
#define   SR_FILETYPE      201
#define   SR_FILECLASS     202
#define   SR_PAL           203
#define   SR_WIDTH         204
#define   SR_HEIGHT        205
#define   SR_SIZE          206
#define   SR_PERCENT       207
#define   SR_ABORT         IDCANCEL


/*************** OPEN and SAVE dialogs **************************************/

#define  CPI_HLSTRCOPY     0x0200
#define  MSG_DU_ERROR      0x0800
#define  MSG_UPDATE_EDITS      0x0801

#define  DUTYPEPATH        1
#define  DUTYPEFILE        2

#define   ID_OK             98
#define   ID_CANCEL         99
#define   DU_FILENAME      200
#define   DU_PATH          201
#define   DU_FILELIST      202
#define   DU_DIRLIST       203
#define   DU_FILETYPE      204
#define   DU_DEFPATH       205
#define   DU_DEFEXT        206


#define   ACC_CLOSE          100
