

#define  ID_IMPORTIMG             150
#define  ID_EXPORTIMG             151
#define  ID_DISPLAYIMG            149
#define  ID_SAVEOPS               141

#define  ID_FILENAME              200
#define  ID_PATH                  201
#define  ID_EDIT                  202
#define  ID_LISTBOX               203



/*---------------------------- DISPLAY STATE DLG ---------------------------*/

#define  ID_PALBASE               200
#define  ID_NORM                  200
#define  ID_OPT                   201
#define  ID_GRAY                  202
#define  ID_BW                    203

#define  ID_DITHBASE              300
#define  ID_NONE                  300
#define  ID_BAYER                 301
#define  ID_FS                    302
#define  ID_NONE16                303
#define  ID_FS16                  304
