
extern      HANDLE      hInstance;               
extern      HANDLE      hStringBuf;
extern      HANDLE      hStructBuf;
extern      HANDLE      hNameBuf;
extern      PSTR        pNameBuf;
extern      char        *FileSpec;
extern      BYTE        ModiFlags;
extern      BYTE        bSharpFilter;
extern      BYTE        bSmoothFilter;
extern      BYTE        bDirection;
extern      BYTE        bScaleProcess;
extern      BYTE        bScaleUnits;
extern      BYTE        bMaintainAspect;
extern      char        SourcePath [128];
extern      char        DestPath   [128];
extern      PSTR        pFullSourceName; 
extern      PSTR        pFullDestName;
extern      PSTR        pFullTempName;
extern      int         nRetval;       
extern      BOOL        bAbandon;
extern      int         nGlobalErr;    
extern      BOOL        b1stSharpen;
extern      BOOL        b1stSmooth;
extern      BOOL        b1stEnhanceEdge;
extern      BOOL        b1stRotate;
extern      BOOL        b1stScale;
extern      BOOL        b1stFlip;
extern      BOOL        b1stMirror;
extern      char        CurrWDir [128];
extern      SHARP       Sharp;
extern      SMOOTH      Smooth;
extern      EDGE        Edge;
extern      ROTATE      Rotate;
extern      SCALE       Scale;
extern      FLIP        Flip;
extern      MIRROR      Mirror;























